export default {
  easy: {
    name: "EASY",
    roundTime: 30,
    timeBtwAppear: [0.5, 1.25],
    appearTime: [1, 2],
    maxHealth: 3,
    extraTime: 1,
    extraTimePercent: 0.3,
    obtainedCoin: 1,
  },
  normal: {
    name: "NORMAL",
    roundTime: 30,
    timeBtwAppear: [0.25, 1],
    appearTime: [0.75, 1.75],
    maxHealth: 3,
    extraTime: 1,
    extraTimePercent: 0.2,
    obtainedCoin: 2,
  },
  hard: {
    name: "HARD",
    roundTime: 30,
    timeBtwAppear: [0.01, 0.75],
    appearTime: [0.5, 1.5],
    maxHealth: 3,
    extraTime: 1,
    extraTimePercent: 0.2,
    obtainedCoin: 3,
  },
};
